### ISSUE TITLE
Add Kubelet GC to sample inventories

### ISSUE THREAD

**Issue by makentenza** [redhat-cop/casl-ansible#161]
Add Kubelet GC entries to sample inventories:

```
### Kubelet GC config
openshift_node_kubelet_args:
  minimum-container-ttl-duration:
  - "10s"
  maximum-dead-containers-per-container:
  - "2"
  maximum-dead-containers:
  - "50"
  pods-per-core:
  - '10'
  max-pods:
  - '250'
  image-gc-high-threshold:
  - '80'
  image-gc-low-threshold:
  - '60'
```
