### ISSUE TITLE
Applier should support iterating over a directory of parameter files in a single item.

### ISSUE THREAD

**Issue by etsauer** [redhat-cop/casl-ansible#195]
I would like to be able to support a situation like this:

```
openshift_cluster_content:
- object: manage sanbox environments
  content:
  - name: create projects
    template: templates/projectrequest.yml
    params: params/sanboxes/
    template_action: create
  - name: map users and groups
    template: templates/sandbox-rolebindings.yml
    params: params/sandboxes/
```

Where `params/sandboxes/` is a directory of parameter files for that template.
