### ISSUE TITLE
openshift-applier: Allow some content to be "created" instead of "applied" for idempotency

### ISSUE THREAD

**Issue by InfoSec812** [redhat-cop/casl-ansible#98]
When using oc-applier to create persistent databases with generate credentials, subsequent runs of the inventory will overwrite the secrets stored in OpenShift but have no effect on the database itself. I propose added an optional field in the inventory so that a particular template is applied once and only once on a given cluster. For example:

```
- object: someobjects
  content:
  - name: ephemeraldb
    template: openshift//mysql-ephemeral
    namespace: my-project
    params: "{{ inventory_dir }}/../params/ephemeraldb/build_params"
  - name: persistentdb
    template: openshift//mysql-persistent
    namespace: my-project
    params: "{{ inventory_dir }}/../params/persistentdb/build_params"
    idempotent: true
```

Inside of of this project, we create a copy of `roles/oc-apply/tasks/process-content.yml` and name it `roles/oc-apply/tasks/process-idempotent.yml`. This task will be modified to ONLY run when `idempotent` is defined and the original will be modified to ONLY run when idempotent is undefined. The new task will use `oc create` along with `oc process` instead of using `oc apply`. The new task would also swallow errors related to the objects already existing.
